// <auto-generated />
using System;
using Do_an_II.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Do_an_II.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250311083951_AddTblProduct")]
    partial class AddTblProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Do_an_II.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Do_an_II.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Color = "Đen",
                            CreatedAt = new DateTime(2025, 3, 11, 15, 39, 49, 279, DateTimeKind.Local).AddTicks(6027),
                            Description = "Áo thun nam",
                            ImageUrl = "~/img/product1",
                            IsActive = true,
                            Material = "Cotton",
                            Name = "Áo thun",
                            Price = 100m,
                            Quantity = 10,
                            Size = "M",
                            UpdatedAt = new DateTime(2025, 3, 11, 15, 39, 49, 279, DateTimeKind.Local).AddTicks(6038)
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Color = "Trắng",
                            CreatedAt = new DateTime(2025, 3, 11, 15, 39, 49, 279, DateTimeKind.Local).AddTicks(6051),
                            Description = "Áo sơ mi nam",
                            ImageUrl = "~/img/product2",
                            IsActive = true,
                            Material = "Vải",
                            Name = "Áo sơ mi",
                            Price = 200m,
                            Quantity = 20,
                            Size = "L",
                            UpdatedAt = new DateTime(2025, 3, 11, 15, 39, 49, 279, DateTimeKind.Local).AddTicks(6051)
                        });
                });

            modelBuilder.Entity("Do_an_II.Models.Product", b =>
                {
                    b.HasOne("Do_an_II.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
